import { db } from "@/db";
import { projectsTable } from "../schema";
import { generateSlug, generateShareUrl } from "@/lib/slug-generator";
import type { TechStack } from "../types/projectTypes";

const projects = [
  {
    id: "ecommerce-platform",
    title: "E-Commerce Platform",
    description: "Full-stack e-commerce solution with modern UI and secure payments",
    overview: "A comprehensive e-commerce platform built with Next.js and TypeScript.",
    role: "Full-Stack Developer",
    techStack: { frontend: ["Next.js", "TypeScript", "Tailwind CSS"], backend: ["Node.js", "Express.js"], database: ["PostgreSQL"], infrastructure: ["Vercel"] } as TechStack,
    architecture: { layers: [{ name: "Frontend", description: "Next.js app" }], notes: "Monolithic" },
    frontendRendering: "SSR" as const,
    mobileSupport: true,
    features: ["User auth", "Product catalog", "Shopping cart"],
    challenges: ["Payment processing", "Database optimization"],
    results: ["500+ daily transactions", "35% reduced abandonment"],
    images: { main: "https://picsum.photos/800/600?random=1", others: [{ url: "https://picsum.photos/800/600?random=2", type: "screenshot" as const, caption: "Dashboard" }] },
    liveDemo: "https://demo1.com",
    sourceCode: "https://github.com/user/project1",
    category: "fullstack" as const,
    status: "completed" as const,
    startDate: "2024-01-15",
    endDate: "2024-03-20",
    tags: ["E-commerce", "Payment"],
    whyItMatters: "Demonstrates full-stack skills",
    isFeatured: true,
    viewCount: 245
  },
  {
    id: "task-management",
    title: "Task Management App",
    description: "Collaborative task management tool with real-time updates",
    overview: "Modern task management application with kanban boards.",
    role: "Frontend Developer",
    techStack: { frontend: ["React", "TypeScript"], backend: ["Express.js"], database: ["MongoDB"], infrastructure: ["AWS"] } as TechStack,
    architecture: { layers: [{ name: "Client", description: "React SPA" }], notes: "Microservices" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Drag-and-drop", "Real-time updates", "Team management"],
    challenges: ["Real-time sync", "Performance optimization"],
    results: ["50+ teams deployed", "40% efficiency increase"],
    images: { main: "https://picsum.photos/800/600?random=3", others: [{ url: "https://picsum.photos/800/600?random=4", type: "screenshot" as const, caption: "Kanban" }] },
    liveDemo: "https://demo2.com",
    sourceCode: "https://github.com/user/project2",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2023-09-10",
    endDate: "2023-12-15",
    tags: ["Real-time", "Collaboration"],
    whyItMatters: "Shows real-time app expertise",
    isFeatured: false,
    viewCount: 128
  },
  {
    id: "social-media-dashboard",
    title: "Social Media Dashboard",
    description: "Analytics dashboard for social media management",
    overview: "Comprehensive dashboard for managing multiple social media accounts.",
    role: "Full-Stack Developer",
    techStack: { frontend: ["Vue.js", "TypeScript"], backend: ["Node.js"], database: ["PostgreSQL"], infrastructure: ["DigitalOcean"] } as TechStack,
    architecture: { layers: [{ name: "Frontend", description: "Vue.js SPA" }], notes: "REST API" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Multi-platform integration", "Analytics", "Scheduling"],
    challenges: ["API rate limits", "Data visualization"],
    results: ["1000+ users", "50% time savings"],
    images: { main: "https://picsum.photos/800/600?random=5", others: [{ url: "https://picsum.photos/800/600?random=6", type: "screenshot" as const, caption: "Analytics" }] },
    liveDemo: "https://demo3.com",
    sourceCode: "https://github.com/user/project3",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2023-06-01",
    endDate: "2023-08-30",
    tags: ["Analytics", "Social Media"],
    whyItMatters: "Data visualization skills",
    isFeatured: true,
    viewCount: 189
  },
  {
    id: "mobile-fitness-app",
    title: "Mobile Fitness App",
    description: "Cross-platform fitness tracking mobile application",
    overview: "Native mobile app for workout tracking and fitness goals.",
    role: "Mobile Developer",
    techStack: { frontend: ["React"], backend: ["Node.js"], database: ["MongoDB"], infrastructure: ["AWS"] } as TechStack,
    architecture: { layers: [{ name: "Mobile", description: "React Native" }], notes: "Cross-platform" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Workout tracking", "Progress analytics", "Social features"],
    challenges: ["Offline sync", "Battery optimization"],
    results: ["10k+ downloads", "4.8 star rating"],
    images: { main: "https://picsum.photos/800/600?random=7", others: [{ url: "https://picsum.photos/800/600?random=8", type: "screenshot" as const, caption: "Workout" }] },
    liveDemo: "https://demo4.com",
    sourceCode: "https://github.com/user/project4",
    category: "mobile" as const,
    status: "completed" as const,
    startDate: "2023-03-01",
    endDate: "2023-05-15",
    tags: ["Mobile", "Fitness"],
    whyItMatters: "Mobile development expertise",
    isFeatured: false,
    viewCount: 156
  },
  {
    id: "inventory-system",
    title: "Inventory Management System",
    description: "Enterprise inventory management with barcode scanning",
    overview: "Complete inventory solution for warehouse management.",
    role: "Backend Developer",
    techStack: { frontend: ["Angular"], backend: ["Java", "Spring Boot"], database: ["MySQL"], infrastructure: ["Docker"] } as TechStack,
    architecture: { layers: [{ name: "Backend", description: "Spring Boot API" }], notes: "Microservices" },
    frontendRendering: "CSR" as const,
    mobileSupport: false,
    features: ["Barcode scanning", "Stock alerts", "Reporting"],
    challenges: ["Scalability", "Real-time updates"],
    results: ["99.9% uptime", "30% efficiency gain"],
    images: { main: "https://picsum.photos/800/600?random=9", others: [{ url: "https://picsum.photos/800/600?random=10", type: "screenshot" as const, caption: "Dashboard" }] },
    liveDemo: "https://demo5.com",
    sourceCode: "https://github.com/user/project5",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2022-11-01",
    endDate: "2023-02-28",
    tags: ["Enterprise", "Inventory"],
    whyItMatters: "Enterprise system experience",
    isFeatured: false,
    viewCount: 98
  },
  {
    id: "blog-platform",
    title: "Blog Publishing Platform",
    description: "Modern blog platform with markdown support",
    overview: "Full-featured blogging platform with CMS capabilities.",
    role: "Full-Stack Developer",
    techStack: { frontend: ["Gatsby", "React"], backend: ["Node.js"], database: ["MongoDB"], infrastructure: ["Netlify"] } as TechStack,
    architecture: { layers: [{ name: "Static", description: "Gatsby SSG" }], notes: "JAMstack" },
    frontendRendering: "SSG" as const,
    mobileSupport: true,
    features: ["Markdown editor", "SEO optimization", "Comments"],
    challenges: ["SEO optimization", "Content management"],
    results: ["50k+ monthly visitors", "2s load time"],
    images: { main: "https://picsum.photos/800/600?random=11", others: [{ url: "https://picsum.photos/800/600?random=12", type: "screenshot" as const, caption: "Editor" }] },
    liveDemo: "https://demo6.com",
    sourceCode: "https://github.com/user/project6",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2023-01-01",
    endDate: "2023-03-15",
    tags: ["Blog", "CMS"],
    whyItMatters: "Content management expertise",
    isFeatured: true,
    viewCount: 234
  },
  {
    id: "weather-app",
    title: "Weather Forecast App",
    description: "Real-time weather application with location services",
    overview: "Weather app with detailed forecasts and alerts.",
    role: "Frontend Developer",
    techStack: { frontend: ["Svelte", "TypeScript"], backend: ["Node.js"], database: ["Redis"], infrastructure: ["Vercel"] } as TechStack,
    architecture: { layers: [{ name: "Frontend", description: "Svelte SPA" }], notes: "API-first" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Location services", "Weather alerts", "Forecasts"],
    challenges: ["API integration", "Geolocation"],
    results: ["100k+ users", "Real-time updates"],
    images: { main: "https://picsum.photos/800/600?random=13", others: [{ url: "https://picsum.photos/800/600?random=14", type: "screenshot" as const, caption: "Forecast" }] },
    liveDemo: "https://demo7.com",
    sourceCode: "https://github.com/user/project7",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2023-04-01",
    endDate: "2023-04-30",
    tags: ["Weather", "API"],
    whyItMatters: "API integration skills",
    isFeatured: false,
    viewCount: 167
  },
  {
    id: "chat-application",
    title: "Real-time Chat Application",
    description: "Instant messaging app with file sharing",
    overview: "Real-time chat with multimedia support.",
    role: "Full-Stack Developer",
    techStack: { frontend: ["React", "TypeScript"], backend: ["Node.js"], database: ["PostgreSQL"], infrastructure: ["AWS"] } as TechStack,
    architecture: { layers: [{ name: "Real-time", description: "WebSocket" }], notes: "Event-driven" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Real-time messaging", "File sharing", "Group chats"],
    challenges: ["WebSocket scaling", "Message delivery"],
    results: ["1k+ concurrent users", "99% delivery rate"],
    images: { main: "https://picsum.photos/800/600?random=15", others: [{ url: "https://picsum.photos/800/600?random=16", type: "screenshot" as const, caption: "Chat" }] },
    liveDemo: "https://demo8.com",
    sourceCode: "https://github.com/user/project8",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2022-08-01",
    endDate: "2022-10-15",
    tags: ["Chat", "Real-time"],
    whyItMatters: "Real-time communication",
    isFeatured: false,
    viewCount: 145
  },
  {
    id: "portfolio-website",
    title: "Portfolio Website",
    description: "Personal portfolio with project showcase",
    overview: "Modern portfolio website with animations.",
    role: "Frontend Developer",
    techStack: { frontend: ["Next.js", "Tailwind CSS"], backend: [], database: [], infrastructure: ["Vercel"] } as TechStack,
    architecture: { layers: [{ name: "Static", description: "Next.js SSG" }], notes: "Static site" },
    frontendRendering: "SSG" as const,
    mobileSupport: true,
    features: ["Project showcase", "Contact form", "Animations"],
    challenges: ["Performance", "SEO"],
    results: ["Perfect Lighthouse score", "Fast loading"],
    images: { main: "https://picsum.photos/800/600?random=17", others: [{ url: "https://picsum.photos/800/600?random=18", type: "screenshot" as const, caption: "Projects" }] },
    liveDemo: "https://demo9.com",
    sourceCode: "https://github.com/user/project9",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2023-07-01",
    endDate: "2023-07-15",
    tags: ["Portfolio", "Animation"],
    whyItMatters: "Design and animation skills",
    isFeatured: true,
    viewCount: 289
  },
  {
    id: "expense-tracker",
    title: "Expense Tracker",
    description: "Personal finance management application",
    overview: "Track expenses and manage budgets.",
    role: "Full-Stack Developer",
    techStack: { frontend: ["Vue.js"], backend: ["Python", "Django"], database: ["PostgreSQL"], infrastructure: ["Heroku"] } as TechStack,
    architecture: { layers: [{ name: "Backend", description: "Django REST" }], notes: "MVC pattern" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Expense tracking", "Budget planning", "Reports"],
    challenges: ["Data visualization", "Security"],
    results: ["5k+ users", "Financial insights"],
    images: { main: "https://picsum.photos/800/600?random=19", others: [{ url: "https://picsum.photos/800/600?random=20", type: "screenshot" as const, caption: "Budget" }] },
    liveDemo: "https://demo10.com",
    sourceCode: "https://github.com/user/project10",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2022-05-01",
    endDate: "2022-07-30",
    tags: ["Finance", "Tracking"],
    whyItMatters: "Financial app development",
    isFeatured: false,
    viewCount: 123
  },
  {
    id: "recipe-finder",
    title: "Recipe Finder App",
    description: "Discover recipes based on available ingredients",
    overview: "Smart recipe recommendation system.",
    role: "Frontend Developer",
    techStack: { frontend: ["React", "JavaScript"], backend: ["Node.js"], database: ["MongoDB"], infrastructure: ["Netlify"] } as TechStack,
    architecture: { layers: [{ name: "API", description: "Recipe API" }], notes: "Third-party integration" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Ingredient search", "Recipe filters", "Favorites"],
    challenges: ["API optimization", "Search algorithm"],
    results: ["20k+ recipes", "Fast search"],
    images: { main: "https://picsum.photos/800/600?random=21", others: [{ url: "https://picsum.photos/800/600?random=22", type: "screenshot" as const, caption: "Search" }] },
    liveDemo: "https://demo11.com",
    sourceCode: "https://github.com/user/project11",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2023-02-01",
    endDate: "2023-02-28",
    tags: ["Recipe", "Search"],
    whyItMatters: "Search optimization",
    isFeatured: false,
    viewCount: 134
  },
  {
    id: "music-player",
    title: "Music Streaming Player",
    description: "Web-based music player with playlist management",
    overview: "Spotify-like music streaming interface.",
    role: "Frontend Developer",
    techStack: { frontend: ["Angular", "TypeScript"], backend: ["Node.js"], database: ["MongoDB"], infrastructure: ["AWS"] } as TechStack,
    architecture: { layers: [{ name: "Audio", description: "Web Audio API" }], notes: "Media streaming" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Audio streaming", "Playlists", "Search"],
    challenges: ["Audio buffering", "Performance"],
    results: ["Smooth playback", "Low latency"],
    images: { main: "https://picsum.photos/800/600?random=23", others: [{ url: "https://picsum.photos/800/600?random=24", type: "screenshot" as const, caption: "Player" }] },
    liveDemo: "https://demo12.com",
    sourceCode: "https://github.com/user/project12",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2022-12-01",
    endDate: "2023-01-31",
    tags: ["Music", "Streaming"],
    whyItMatters: "Media handling expertise",
    isFeatured: false,
    viewCount: 178
  },
  {
    id: "booking-system",
    title: "Hotel Booking System",
    description: "Complete hotel reservation management platform",
    overview: "Full-featured booking system for hotels.",
    role: "Full-Stack Developer",
    techStack: { frontend: ["Next.js", "React"], backend: ["Node.js"], database: ["PostgreSQL"], infrastructure: ["Vercel"] } as TechStack,
    architecture: { layers: [{ name: "Booking", description: "Reservation logic" }], notes: "Complex business logic" },
    frontendRendering: "SSR" as const,
    mobileSupport: true,
    features: ["Room booking", "Payment integration", "Admin panel"],
    challenges: ["Availability logic", "Payment processing"],
    results: ["200+ bookings/day", "Automated system"],
    images: { main: "https://picsum.photos/800/600?random=25", others: [{ url: "https://picsum.photos/800/600?random=26", type: "screenshot" as const, caption: "Booking" }] },
    liveDemo: "https://demo13.com",
    sourceCode: "https://github.com/user/project13",
    category: "fullstack" as const,
    status: "completed" as const,
    startDate: "2022-09-01",
    endDate: "2022-11-30",
    tags: ["Booking", "Hotel"],
    whyItMatters: "Complex business logic",
    isFeatured: true,
    viewCount: 267
  },
  {
    id: "code-editor",
    title: "Online Code Editor",
    description: "Browser-based code editor with syntax highlighting",
    overview: "VS Code-like editor in the browser.",
    role: "Frontend Developer",
    techStack: { frontend: ["React", "TypeScript"], backend: ["Node.js"], database: ["Redis"], infrastructure: ["Docker"] } as TechStack,
    architecture: { layers: [{ name: "Editor", description: "Monaco Editor" }], notes: "Real-time compilation" },
    frontendRendering: "CSR" as const,
    mobileSupport: false,
    features: ["Syntax highlighting", "Auto-completion", "File management"],
    challenges: ["Performance", "Memory management"],
    results: ["Sub-second compilation", "Rich features"],
    images: { main: "https://picsum.photos/800/600?random=27", others: [{ url: "https://picsum.photos/800/600?random=28", type: "screenshot" as const, caption: "Editor" }] },
    liveDemo: "https://demo14.com",
    sourceCode: "https://github.com/user/project14",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2023-05-01",
    endDate: "2023-06-15",
    tags: ["Editor", "Development"],
    whyItMatters: "Developer tools expertise",
    isFeatured: false,
    viewCount: 156
  },
  {
    id: "learning-platform",
    title: "Online Learning Platform",
    description: "Educational platform with video courses",
    overview: "Udemy-like learning management system.",
    role: "Full-Stack Developer",
    techStack: { frontend: ["Vue.js", "Nuxt.js"], backend: ["Python", "FastAPI"], database: ["PostgreSQL"], infrastructure: ["AWS"] } as TechStack,
    architecture: { layers: [{ name: "LMS", description: "Learning management" }], notes: "Video streaming" },
    frontendRendering: "SSR" as const,
    mobileSupport: true,
    features: ["Video courses", "Progress tracking", "Certificates"],
    challenges: ["Video streaming", "Progress tracking"],
    results: ["1000+ students", "High engagement"],
    images: { main: "https://picsum.photos/800/600?random=29", others: [{ url: "https://picsum.photos/800/600?random=30", type: "screenshot" as const, caption: "Course" }] },
    liveDemo: "https://demo15.com",
    sourceCode: "https://github.com/user/project15",
    category: "fullstack" as const,
    status: "completed" as const,
    startDate: "2022-06-01",
    endDate: "2022-08-31",
    tags: ["Education", "Video"],
    whyItMatters: "EdTech experience",
    isFeatured: true,
    viewCount: 298
  },
  {
    id: "cryptocurrency-tracker",
    title: "Cryptocurrency Tracker",
    description: "Real-time crypto price monitoring dashboard",
    overview: "Track cryptocurrency prices and trends.",
    role: "Frontend Developer",
    techStack: { frontend: ["React", "TypeScript"], backend: ["Node.js"], database: ["Redis"], infrastructure: ["Vercel"] } as TechStack,
    architecture: { layers: [{ name: "Real-time", description: "WebSocket data" }], notes: "High-frequency updates" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Price tracking", "Charts", "Alerts"],
    challenges: ["Real-time data", "Chart performance"],
    results: ["Live price updates", "Accurate charts"],
    images: { main: "https://picsum.photos/800/600?random=31", others: [{ url: "https://picsum.photos/800/600?random=32", type: "screenshot" as const, caption: "Charts" }] },
    liveDemo: "https://demo16.com",
    sourceCode: "https://github.com/user/project16",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2023-08-01",
    endDate: "2023-08-31",
    tags: ["Crypto", "Finance"],
    whyItMatters: "Financial data visualization",
    isFeatured: false,
    viewCount: 187
  },
  {
    id: "event-management",
    title: "Event Management System",
    description: "Complete event planning and ticketing platform",
    overview: "Eventbrite-like event management system.",
    role: "Full-Stack Developer",
    techStack: { frontend: ["Angular", "TypeScript"], backend: ["C#", ".NET Core"], database: ["PostgreSQL"], infrastructure: ["Microsoft Azure"] } as TechStack,
    architecture: { layers: [{ name: "Events", description: "Event management" }], notes: "Microservices" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Event creation", "Ticket sales", "Check-in system"],
    challenges: ["Scalability", "Payment processing"],
    results: ["500+ events managed", "Seamless ticketing"],
    images: { main: "https://picsum.photos/800/600?random=33", others: [{ url: "https://picsum.photos/800/600?random=34", type: "screenshot" as const, caption: "Events" }] },
    liveDemo: "https://demo17.com",
    sourceCode: "https://github.com/user/project17",
    category: "fullstack" as const,
    status: "completed" as const,
    startDate: "2022-03-01",
    endDate: "2022-05-31",
    tags: ["Events", "Ticketing"],
    whyItMatters: "Event industry expertise",
    isFeatured: false,
    viewCount: 145
  },
  {
    id: "file-storage",
    title: "Cloud File Storage",
    description: "Dropbox-like file storage and sharing platform",
    overview: "Secure cloud storage with file sharing.",
    role: "Backend Developer",
    techStack: { frontend: ["React"], backend: ["Go"], database: ["PostgreSQL"], infrastructure: ["AWS"] } as TechStack,
    architecture: { layers: [{ name: "Storage", description: "S3 integration" }], notes: "Distributed storage" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["File upload", "Sharing", "Version control"],
    challenges: ["File handling", "Security"],
    results: ["TB+ storage handled", "Secure sharing"],
    images: { main: "https://picsum.photos/800/600?random=35", others: [{ url: "https://picsum.photos/800/600?random=36", type: "screenshot" as const, caption: "Files" }] },
    liveDemo: "https://demo18.com",
    sourceCode: "https://github.com/user/project18",
    category: "fullstack" as const,
    status: "completed" as const,
    startDate: "2022-01-01",
    endDate: "2022-03-31",
    tags: ["Storage", "Cloud"],
    whyItMatters: "Cloud storage expertise",
    isFeatured: false,
    viewCount: 167
  },
  {
    id: "game-leaderboard",
    title: "Gaming Leaderboard",
    description: "Real-time gaming statistics and rankings",
    overview: "Track player statistics and rankings.",
    role: "Backend Developer",
    techStack: { frontend: ["Svelte"], backend: ["Rust"], database: ["Redis"], infrastructure: ["Docker"] } as TechStack,
    architecture: { layers: [{ name: "Gaming", description: "Real-time stats" }], notes: "High performance" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Real-time rankings", "Player stats", "Achievements"],
    challenges: ["Performance", "Real-time updates"],
    results: ["Sub-ms response time", "Concurrent users"],
    images: { main: "https://picsum.photos/800/600?random=37", others: [{ url: "https://picsum.photos/800/600?random=38", type: "screenshot" as const, caption: "Rankings" }] },
    liveDemo: "https://demo19.com",
    sourceCode: "https://github.com/user/project19",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2023-09-01",
    endDate: "2023-09-30",
    tags: ["Gaming", "Real-time"],
    whyItMatters: "High-performance systems",
    isFeatured: false,
    viewCount: 134
  },
  {
    id: "api-documentation",
    title: "API Documentation Platform",
    description: "Interactive API documentation generator",
    overview: "Swagger-like API documentation tool.",
    role: "Full-Stack Developer",
    techStack: { frontend: ["Next.js", "React"], backend: ["Node.js"], database: ["MongoDB"], infrastructure: ["Vercel"] } as TechStack,
    architecture: { layers: [{ name: "Docs", description: "Documentation engine" }], notes: "Static generation" },
    frontendRendering: "SSG" as const,
    mobileSupport: true,
    features: ["Interactive docs", "Code examples", "Testing interface"],
    challenges: ["Code generation", "Interactive examples"],
    results: ["Developer-friendly", "Easy integration"],
    images: { main: "https://picsum.photos/800/600?random=39", others: [{ url: "https://picsum.photos/800/600?random=40", type: "screenshot" as const, caption: "Docs" }] },
    liveDemo: "https://demo20.com",
    sourceCode: "https://github.com/user/project20",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2023-10-01",
    endDate: "2023-10-31",
    tags: ["Documentation", "API"],
    whyItMatters: "Developer experience focus",
    isFeatured: true,
    viewCount: 223
  },
  {
    id: "survey-platform",
    title: "Survey & Polling Platform",
    description: "Create and analyze surveys with real-time results",
    overview: "SurveyMonkey-like survey creation tool.",
    role: "Full-Stack Developer",
    techStack: { frontend: ["Vue.js", "TypeScript"], backend: ["Python", "Django"], database: ["PostgreSQL"], infrastructure: ["DigitalOcean"] } as TechStack,
    architecture: { layers: [{ name: "Survey", description: "Form builder" }], notes: "Dynamic forms" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Survey builder", "Analytics", "Export data"],
    challenges: ["Dynamic forms", "Data analysis"],
    results: ["10k+ surveys created", "Rich analytics"],
    images: { main: "https://picsum.photos/800/600?random=41", others: [{ url: "https://picsum.photos/800/600?random=42", type: "screenshot" as const, caption: "Builder" }] },
    liveDemo: "https://demo21.com",
    sourceCode: "https://github.com/user/project21",
    category: "fullstack" as const,
    status: "completed" as const,
    startDate: "2022-10-01",
    endDate: "2022-12-31",
    tags: ["Survey", "Analytics"],
    whyItMatters: "Data collection expertise",
    isFeatured: false,
    viewCount: 156
  },
  {
    id: "video-conferencing",
    title: "Video Conferencing App",
    description: "Zoom-like video calling platform",
    overview: "WebRTC-based video conferencing solution.",
    role: "Full-Stack Developer",
    techStack: { frontend: ["React", "TypeScript"], backend: ["Node.js"], database: ["MongoDB"], infrastructure: ["AWS"] } as TechStack,
    architecture: { layers: [{ name: "WebRTC", description: "Peer-to-peer video" }], notes: "Real-time communication" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Video calls", "Screen sharing", "Chat"],
    challenges: ["WebRTC implementation", "Scalability"],
    results: ["HD video quality", "Low latency"],
    images: { main: "https://picsum.photos/800/600?random=43", others: [{ url: "https://picsum.photos/800/600?random=44", type: "screenshot" as const, caption: "Call" }] },
    liveDemo: "https://demo22.com",
    sourceCode: "https://github.com/user/project22",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2023-11-01",
    endDate: "2023-12-15",
    tags: ["Video", "WebRTC"],
    whyItMatters: "Real-time communication",
    isFeatured: true,
    viewCount: 312
  },
  {
    id: "job-board",
    title: "Job Board Platform",
    description: "Indeed-like job posting and application platform",
    overview: "Complete job marketplace with matching.",
    role: "Full-Stack Developer",
    techStack: { frontend: ["Angular", "TypeScript"], backend: ["Java", "Spring Boot"], database: ["PostgreSQL"], infrastructure: ["Docker"] } as TechStack,
    architecture: { layers: [{ name: "Matching", description: "Job matching algorithm" }], notes: "Search optimization" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Job posting", "Application tracking", "Matching algorithm"],
    challenges: ["Search optimization", "Matching algorithm"],
    results: ["1000+ job postings", "High match accuracy"],
    images: { main: "https://picsum.photos/800/600?random=45", others: [{ url: "https://picsum.photos/800/600?random=46", type: "screenshot" as const, caption: "Jobs" }] },
    liveDemo: "https://demo23.com",
    sourceCode: "https://github.com/user/project23",
    category: "fullstack" as const,
    status: "completed" as const,
    startDate: "2022-07-01",
    endDate: "2022-09-30",
    tags: ["Jobs", "Matching"],
    whyItMatters: "Algorithm development",
    isFeatured: false,
    viewCount: 189
  },
  {
    id: "news-aggregator",
    title: "News Aggregator",
    description: "Multi-source news aggregation with personalization",
    overview: "Reddit-like news aggregation platform.",
    role: "Backend Developer",
    techStack: { frontend: ["React"], backend: ["Python", "FastAPI"], database: ["PostgreSQL"], infrastructure: ["AWS"] } as TechStack,
    architecture: { layers: [{ name: "Aggregation", description: "News scraping" }], notes: "Data pipeline" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["News aggregation", "Personalization", "Trending topics"],
    challenges: ["Data scraping", "Content filtering"],
    results: ["1M+ articles processed", "Personalized feeds"],
    images: { main: "https://picsum.photos/800/600?random=47", others: [{ url: "https://picsum.photos/800/600?random=48", type: "screenshot" as const, caption: "Feed" }] },
    liveDemo: "https://demo24.com",
    sourceCode: "https://github.com/user/project24",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2023-03-01",
    endDate: "2023-04-30",
    tags: ["News", "Aggregation"],
    whyItMatters: "Data processing expertise",
    isFeatured: false,
    viewCount: 167
  },
  {
    id: "marketplace",
    title: "Online Marketplace",
    description: "eBay-like marketplace with seller tools",
    overview: "Multi-vendor marketplace platform.",
    role: "Full-Stack Developer",
    techStack: { frontend: ["Next.js", "React"], backend: ["Node.js"], database: ["PostgreSQL"], infrastructure: ["Vercel"] } as TechStack,
    architecture: { layers: [{ name: "Marketplace", description: "Multi-vendor system" }], notes: "Complex business logic" },
    frontendRendering: "SSR" as const,
    mobileSupport: true,
    features: ["Multi-vendor support", "Payment processing", "Review system"],
    challenges: ["Multi-tenancy", "Payment splitting"],
    results: ["100+ vendors", "Secure transactions"],
    images: { main: "https://picsum.photos/800/600?random=49", others: [{ url: "https://picsum.photos/800/600?random=50", type: "screenshot" as const, caption: "Products" }] },
    liveDemo: "https://demo25.com",
    sourceCode: "https://github.com/user/project25",
    category: "fullstack" as const,
    status: "completed" as const,
    startDate: "2022-04-01",
    endDate: "2022-06-30",
    tags: ["Marketplace", "E-commerce"],
    whyItMatters: "Complex marketplace logic",
    isFeatured: true,
    viewCount: 278
  },
  {
    id: "analytics-dashboard",
    title: "Analytics Dashboard",
    description: "Google Analytics-like web analytics platform",
    overview: "Comprehensive web analytics solution.",
    role: "Full-Stack Developer",
    techStack: { frontend: ["Vue.js", "TypeScript"], backend: ["Node.js"], database: ["InfluxDB"], infrastructure: ["AWS"] } as TechStack,
    architecture: { layers: [{ name: "Analytics", description: "Time-series data" }], notes: "Big data processing" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Real-time analytics", "Custom reports", "Data visualization"],
    challenges: ["Big data processing", "Real-time updates"],
    results: ["TB+ data processed", "Real-time insights"],
    images: { main: "https://picsum.photos/800/600?random=51", others: [{ url: "https://picsum.photos/800/600?random=52", type: "screenshot" as const, caption: "Analytics" }] },
    liveDemo: "https://demo26.com",
    sourceCode: "https://github.com/user/project26",
    category: "fullstack" as const,
    status: "completed" as const,
    startDate: "2023-06-01",
    endDate: "2023-08-31",
    tags: ["Analytics", "Big Data"],
    whyItMatters: "Big data expertise",
    isFeatured: true,
    viewCount: 345
  },
  {
    id: "crm-system",
    title: "Customer Relationship Management",
    description: "Salesforce-like CRM with automation",
    overview: "Complete CRM solution for businesses.",
    role: "Full-Stack Developer",
    techStack: { frontend: ["Angular", "TypeScript"], backend: ["C#", ".NET Core"], database: ["PostgreSQL"], infrastructure: ["Microsoft Azure"] } as TechStack,
    architecture: { layers: [{ name: "CRM", description: "Customer management" }], notes: "Enterprise architecture" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Contact management", "Sales pipeline", "Automation"],
    challenges: ["Complex workflows", "Data relationships"],
    results: ["Enterprise deployment", "Workflow automation"],
    images: { main: "https://picsum.photos/800/600?random=53", others: [{ url: "https://picsum.photos/800/600?random=54", type: "screenshot" as const, caption: "Pipeline" }] },
    liveDemo: "https://demo27.com",
    sourceCode: "https://github.com/user/project27",
    category: "fullstack" as const,
    status: "completed" as const,
    startDate: "2021-10-01",
    endDate: "2022-01-31",
    tags: ["CRM", "Enterprise"],
    whyItMatters: "Enterprise software development",
    isFeatured: false,
    viewCount: 198
  },
  {
    id: "delivery-tracking",
    title: "Delivery Tracking System",
    description: "Real-time package tracking with GPS integration",
    overview: "UberEats-like delivery tracking system.",
    role: "Full-Stack Developer",
    techStack: { frontend: ["React", "TypeScript"], backend: ["Node.js"], database: ["MongoDB"], infrastructure: ["AWS"] } as TechStack,
    architecture: { layers: [{ name: "Tracking", description: "GPS integration" }], notes: "Real-time location" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Real-time tracking", "GPS integration", "Notifications"],
    challenges: ["GPS accuracy", "Real-time updates"],
    results: ["Accurate tracking", "Real-time notifications"],
    images: { main: "https://picsum.photos/800/600?random=55", others: [{ url: "https://picsum.photos/800/600?random=56", type: "screenshot" as const, caption: "Map" }] },
    liveDemo: "https://demo28.com",
    sourceCode: "https://github.com/user/project28",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2023-01-01",
    endDate: "2023-02-28",
    tags: ["Tracking", "GPS"],
    whyItMatters: "Location-based services",
    isFeatured: false,
    viewCount: 145
  },
  {
    id: "password-manager",
    title: "Password Manager",
    description: "Secure password storage with encryption",
    overview: "1Password-like secure password manager.",
    role: "Security Developer",
    techStack: { frontend: ["Svelte", "TypeScript"], backend: ["Rust"], database: ["SQLite"], infrastructure: ["Docker"] } as TechStack,
    architecture: { layers: [{ name: "Security", description: "End-to-end encryption" }], notes: "Zero-knowledge architecture" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Password generation", "Secure storage", "Auto-fill"],
    challenges: ["Encryption", "Security auditing"],
    results: ["Military-grade encryption", "Zero breaches"],
    images: { main: "https://picsum.photos/800/600?random=57", others: [{ url: "https://picsum.photos/800/600?random=58", type: "screenshot" as const, caption: "Vault" }] },
    liveDemo: "https://demo29.com",
    sourceCode: "https://github.com/user/project29",
    category: "web" as const,
    status: "completed" as const,
    startDate: "2023-12-01",
    endDate: "2024-01-15",
    tags: ["Security", "Encryption"],
    whyItMatters: "Security expertise",
    isFeatured: true,
    viewCount: 267
  },
  {
    id: "ai-chatbot",
    title: "AI Customer Support Chatbot",
    description: "Intelligent chatbot with natural language processing",
    overview: "ChatGPT-like customer support automation.",
    role: "AI Developer",
    techStack: { frontend: ["React", "TypeScript"], backend: ["Python", "FastAPI"], database: ["PostgreSQL"], infrastructure: ["AWS"] } as TechStack,
    architecture: { layers: [{ name: "AI", description: "NLP processing" }], notes: "Machine learning pipeline" },
    frontendRendering: "CSR" as const,
    mobileSupport: true,
    features: ["Natural language processing", "Intent recognition", "Learning system"],
    challenges: ["NLP accuracy", "Training data"],
    results: ["90% accuracy rate", "24/7 support"],
    images: { main: "https://picsum.photos/800/600?random=59", others: [{ url: "https://picsum.photos/800/600?random=60", type: "screenshot" as const, caption: "Chat" }] },
    liveDemo: "https://demo30.com",
    sourceCode: "https://github.com/user/project30",
    category: "api" as const,
    status: "completed" as const,
    startDate: "2024-02-01",
    endDate: "2024-03-31",
    tags: ["AI", "Chatbot"],
    whyItMatters: "AI and machine learning expertise",
    isFeatured: true,
    viewCount: 389
  }
];

export async function seedProjects() {
  try {
    console.log("🌱 Seeding projects...");

    for (const project of projects) {
      const slug = generateSlug(project.title);
      const shareUrl = generateShareUrl(slug);

      const projectWithSharing = {
        ...project,
        slug,
        shareUrl,
        isPublic: true,
      };

      await db
        .insert(projectsTable)
        .values(projectWithSharing)
        .onConflictDoUpdate({
          target: projectsTable.id,
          set: {
            title: project.title,
            description: project.description,
            overview: project.overview,
            role: project.role,
            techStack: project.techStack,
            architecture: project.architecture,
            frontendRendering: project.frontendRendering,
            mobileSupport: project.mobileSupport,
            features: project.features,
            challenges: project.challenges,
            results: project.results,
            images: project.images,
            liveDemo: project.liveDemo,
            sourceCode: project.sourceCode,
            category: project.category,
            status: project.status,
            startDate: project.startDate,
            endDate: project.endDate,
            tags: project.tags,
            whyItMatters: project.whyItMatters,
            isFeatured: project.isFeatured,
            viewCount: project.viewCount,
            slug,
            shareUrl,
            isPublic: true,
          },
        });
      console.log(`✅ Seeded project: ${project.title}`);
    }

    console.log("🎉 Projects seeded successfully!");
  } catch (error) {
    console.error("❌ Error seeding projects:", error);
    throw error;
  }
}