CREATE TABLE IF NOT EXISTS "projects" (
	"id" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"overview" text NOT NULL,
	"role" text NOT NULL,
	"tech_stack" json NOT NULL,
	"architecture" text NOT NULL,
	"frontend_rendering" text NOT NULL,
	"mobile_support" boolean DEFAULT false NOT NULL,
	"features" json NOT NULL,
	"challenges" json NOT NULL,
	"results" text NOT NULL,
	"images" json NOT NULL,
	"live_demo" text,
	"source_code" text,
	"category" text NOT NULL,
	"status" text NOT NULL,
	"start_date" text NOT NULL,
	"end_date" text,
	"tags" json NOT NULL,
	"why_it_matters" text,
	"is_featured" boolean DEFAULT false NOT NULL,
	"view_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);