CREATE TYPE "public"."role" AS ENUM('USER', 'ADMIN');--> statement-breakpoint
CREATE TABLE "projects" (
	"id" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"overview" text NOT NULL,
	"role" text NOT NULL,
	"tech_stack" json NOT NULL,
	"architecture" text NOT NULL,
	"frontend_rendering" text NOT NULL,
	"mobile_support" boolean DEFAULT false NOT NULL,
	"features" json NOT NULL,
	"challenges" json NOT NULL,
	"results" text NOT NULL,
	"images" json NOT NULL,
	"live_demo" text,
	"source_code" text,
	"category" text NOT NULL,
	"status" text NOT NULL,
	"start_date" text NOT NULL,
	"end_date" text,
	"tags" json NOT NULL,
	"why_it_matters" text,
	"is_featured" boolean DEFAULT false NOT NULL,
	"view_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"uuid" varchar(255) PRIMARY KEY NOT NULL,
	"google_id" varchar(100),
	"name" varchar(100) NOT NULL,
	"email" varchar(100) NOT NULL,
	"password" text,
	"profile_image" text DEFAULT '/default.png',
	"phone" varchar(20),
	"bio" text,
	"gender" varchar(10),
	"otp" varchar(10),
	"otp_expires_at" timestamp with time zone,
	"token" text,
	"verified" boolean DEFAULT false,
	"role" "role" DEFAULT 'USER' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "users_google_id_unique" UNIQUE("google_id"),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
